### PR TITLE
Delfin User Interface Requirements & Design document

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind design

**What this PR does / why we need it**:
This PR proposes the design specifications, requirements, analysis and architecture for the user interface integration of Delfin APIs
**Which issue(s) this PR fixes**:
Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
Please create a folder say, for example, resources, inside the dashboard, and move all the images inside that.

**Comment by anvithks** [comment]
> Please create a folder say, for example, resources, inside the dashboard, and move all the images inside that.

Will do. Used the github uploader but could not find a way to create a folder.

**Comment by anvithks** [comment]
@kumarashit I have updated the design with overall architecture view and prototype design. I will update this document when I have more information regarding the performance metrics APIs.

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
